# Generated by Django 5.0.2 on 2025-06-25 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_ecole', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('emplacement', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('identifiant', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('site_web', models.URLField(blank=True, max_length=2000, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notation', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('admission', models.CharField(blank=True, max_length=50, null=True)),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_a', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ecole',
                'verbose_name_plural': 'Ecoles',
                'ordering': ['-cree_a'],
            },
        ),
        migrations.CreateModel(
            name='EcoleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecoles.ecole')),
            ],
            options={
                'verbose_name': 'Image Ecole',
                'verbose_name_plural': 'Images Ecoles',
                'ordering': ['cree_a'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duree', models.CharField(max_length=100)),
                ('type_de_degre', models.CharField(max_length=100)),
                ('cout_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cout_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('identifiant', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('devise', models.CharField(blank=True, max_length=10, null=True)),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
                ('identifiant_ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_scolaires', to='ecoles.ecole', to_field='identifiant')),
            ],
            options={
                'verbose_name': 'Programme Scolaire',
                'verbose_name_plural': 'Programmes Scolaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=255)),
                ('email_de_l_etudiant', models.EmailField(max_length=254)),
                ('telephone_etudiant', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('passeport_cin', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('niveau_d_education', models.CharField(blank=True, max_length=100, null=True)),
                ('master_one_code', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_du_lycee', models.CharField(blank=True, max_length=255, null=True)),
                ('annee_d_obtention_du_bac', models.CharField(blank=True, max_length=4, null=True)),
                ('bac_series', models.CharField(blank=True, max_length=100, null=True)),
                ('moyenne_bac_regionale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_nationale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
                ('civilite', models.CharField(blank=True, max_length=10, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('documents_telecharger', models.JSONField(blank=True, null=True)),
                ('id_de_l_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_inscriptions', to=settings.AUTH_USER_MODEL)),
                ('identifiant_ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_inscriptions', to='ecoles.ecole', to_field='identifiant')),
                ('programme_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='ecoles.programmescolaire', to_field='identifiant')),
            ],
            options={
                'verbose_name': 'Pré-inscription',
                'verbose_name_plural': 'Pré-inscriptions',
                'ordering': ['-cree_a'],
            },
        ),
        migrations.CreateModel(
            name='FavorisUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
                ('id_de_l_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
                ('identifiant_ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='ecoles.ecole', to_field='identifiant')),
            ],
            options={
                'verbose_name': 'Favori Utilisateur',
                'verbose_name_plural': 'Favoris Utilisateurs',
                'ordering': ['-cree_a'],
                'unique_together': {('id_de_l_utilisateur', 'identifiant_ecole')},
            },
        ),
    ]
