# Generated by Django 5.0.2 on 2025-06-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(help_text="Classe Font Awesome de l'icône (ex: fas fa-flask)", max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caractéristique Ecole',
                'verbose_name_plural': 'Caractéristiques Ecoles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ecole',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='ecoles', to='ecoles.ecolefeature'),
        ),
    ]
