# Generated by Django 5.0.2 on 2025-06-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0002_ecolefeature_ecole_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Ex: Université, École d'ingénieurs, École de commerce, Lycée", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Type d'école",
                'verbose_name_plural': "Types d'écoles",
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='ecole',
            name='type_ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoles_par_type', to='ecoles.typeecole'),
        ),
    ]
