# Generated by Django 5.0.2 on 2025-06-27 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0003_typeecole_alter_ecole_type_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='identifiant',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
