# Generated by Django 5.0.2 on 2025-06-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0004_preinscription_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='support_tech_msg',
            field=models.CharField(blank=True, default='Votre demande est en attente de traitement. Nous examinerons votre dossier dans les plus brefs délais.', max_length=500, null=True),
        ),
    ]
