# Generated by Django 5.0.2 on 2025-06-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0005_preinscription_support_tech_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='bac_diploma',
            field=models.FileField(blank=True, null=True, upload_to='pre_inscriptions/bac_diplomas/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='cni_copy',
            field=models.FileField(blank=True, null=True, upload_to='pre_inscriptions/cni_copies/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='pre_inscriptions/cvs/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='ecole_actuelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='pre_inscriptions/lettres_motivation/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pre_inscriptions/photos/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='recommandation',
            field=models.FileField(blank=True, null=True, upload_to='pre_inscriptions/recommandations/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='releve_notes',
            field=models.FileField(blank=True, null=True, upload_to='pre_inscriptions/releves_notes/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='ville_actuelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
