# Generated by Django 5.0.2 on 2025-06-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0006_preinscription_bac_diploma_preinscription_cni_copy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='features',
        ),
        migrations.DeleteModel(
            name='EcoleFeature',
        ),
    ]
