# Generated by Django 4.2.7 on 2025-07-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0007_remove_ecole_features_delete_ecolefeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscription',
            name='annee_d_obtention_du_bac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
