# Generated by Django 4.2.7 on 2025-07-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0008_alter_preinscription_annee_d_obtention_du_bac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscription',
            name='moyenne_nationale',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='niveau_d_education',
        ),
    ]
