# Generated by Django 4.2.7 on 2025-07-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0010_remove_ecoleimage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='ville',
        ),
    ]
