# Generated by Django 4.2.7 on 2025-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0011_remove_ecole_adresse_remove_ecole_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='ville',
            field=models.CharField(default='Fès', max_length=255),
            preserve_default=False,
        ),
    ]
