# Generated by Django 4.2.7 on 2025-07-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0012_ecole_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmescolaire',
            name='cout_min',
        ),
    ]
