# Generated by Django 4.2.7 on 2025-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0013_remove_programmescolaire_cout_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=18, null=True),
        ),
    ]
