# Generated by Django 5.0.2 on 2025-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandevisite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AddField(
            model_name='demandevisite',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
