# Generated by Django 4.2.7 on 2025-07-04 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0002_demandevisite_email_demandevisite_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandevisite',
            name='identifiant',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant unique demande'),
        ),
    ]
