# Generated by Django 5.0.2 on 2025-06-30 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSupportTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MessageSupport',
                'verbose_name_plural': 'MessageSupports',
                'ordering': ['-cree_a'],
            },
        ),
    ]
